name: Event
on:
  push:
      branches: [master]
  repository_dispatch:
    types: [uweb3event]
jobs:
  testrunner:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:latest
        env:
            MYSQL_DATABASE: aquarium
            MYSQL_USER: uweb3test
            MYSQL_PASSWORD: uweb3test
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      # - name: Run uweb3tests
      #   run: |
      #     python3 -m unittest testrunner
  build:
    runs-on: ubuntu-latest
    
